package com.ewing.busi.pay.model;

// Generated 2016-4-7 9:57:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PayHistory generated by hbm2java
 */
public class PayHistory implements java.io.Serializable {

    private Integer id;
    private String bizId;
    private String busiType;
    private int busiId;
    private String payWay;
    private int customerId;
    private int userId;
    private float payFee;
    private String status;
    private String comment;
    private Date createTime;
    private Date lastUpdate;

    public PayHistory() {
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getBizId() {
        return this.bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public String getBusiType() {
        return this.busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    public int getBusiId() {
        return this.busiId;
    }

    public void setBusiId(int busiId) {
        this.busiId = busiId;
    }

    public String getPayWay() {
        return this.payWay;
    }

    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public float getPayFee() {
        return this.payFee;
    }

    public void setPayFee(float payFee) {
        this.payFee = payFee;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
