package com.admin.model;
// Generated 2015-10-10 22:43:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WebResourceSpec generated by hbm2java
 */
public class WebResourceSpec implements java.io.Serializable {

	private Integer id;
	private int resourceId;
	private String specCode;
	private String cost;
	private String price;
	private String giftScore;
	private Integer stockNum;
	private String iseff;
	private Date createTime;
	private Date lastUpdate;

	public WebResourceSpec() {
	}

	public WebResourceSpec(int resourceId, String specCode, String iseff,
			Date createTime, Date lastUpdate) {
		this.resourceId = resourceId;
		this.specCode = specCode;
		this.iseff = iseff;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
	}
	public WebResourceSpec(int resourceId, String specCode, String cost,
			String price, String giftScore, Integer stockNum, String iseff,
			Date createTime, Date lastUpdate) {
		this.resourceId = resourceId;
		this.specCode = specCode;
		this.cost = cost;
		this.price = price;
		this.giftScore = giftScore;
		this.stockNum = stockNum;
		this.iseff = iseff;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public int getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(int resourceId) {
		this.resourceId = resourceId;
	}
	public String getSpecCode() {
		return this.specCode;
	}

	public void setSpecCode(String specCode) {
		this.specCode = specCode;
	}
	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}
	public String getGiftScore() {
		return this.giftScore;
	}

	public void setGiftScore(String giftScore) {
		this.giftScore = giftScore;
	}
	public Integer getStockNum() {
		return this.stockNum;
	}

	public void setStockNum(Integer stockNum) {
		this.stockNum = stockNum;
	}
	public String getIseff() {
		return this.iseff;
	}

	public void setIseff(String iseff) {
		this.iseff = iseff;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
