package com.admin.model;
// Generated 2015-10-10 22:43:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WebResourceParam generated by hbm2java
 */
public class WebResourceParam implements java.io.Serializable {

	private Integer id;
	private int resourceId;
	private String paramCode;
	private String paramName;
	private String paramValue;
	private String rootCode;
	private String des;
	private int rank;
	private String iseff;
	private Date createTime;
	private Date lastUpdate;

	public WebResourceParam() {
	}

	public WebResourceParam(int resourceId, String paramCode, String paramName,
			int rank, String iseff, Date createTime, Date lastUpdate) {
		this.resourceId = resourceId;
		this.paramCode = paramCode;
		this.paramName = paramName;
		this.rank = rank;
		this.iseff = iseff;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
	}
	public WebResourceParam(int resourceId, String paramCode, String paramName,
			String paramValue, String rootCode, String des, int rank,
			String iseff, Date createTime, Date lastUpdate) {
		this.resourceId = resourceId;
		this.paramCode = paramCode;
		this.paramName = paramName;
		this.paramValue = paramValue;
		this.rootCode = rootCode;
		this.des = des;
		this.rank = rank;
		this.iseff = iseff;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public int getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(int resourceId) {
		this.resourceId = resourceId;
	}
	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}
	public String getRootCode() {
		return this.rootCode;
	}

	public void setRootCode(String rootCode) {
		this.rootCode = rootCode;
	}
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}
	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}
	public String getIseff() {
		return this.iseff;
	}

	public void setIseff(String iseff) {
		this.iseff = iseff;
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
