package com.ewing.busi.order.model;

// Generated 2016-2-4 17:41:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderInfo generated by hbm2java
 */
public class OrderInfo implements java.io.Serializable {

    private Integer id;
    private int customerId;
    private int userId;
    private String bizId;
    private float productPrice;
    private float cargoPrice;
    private float totalPrice;
    private String status;
    private String receiver;
    private String postCode;
    private String province;
    private String city;
    private String region;
    private String address;
    private String phone;
    /**
     * 是否需要物流
     */
    private Integer needCargo;
    /**
     * 物流公司名称
     */
    private String cargoName;
    /**
     * 物流编号
     */
    private String cargoNumber; 
    /**
     * 修改后运费
     */
    private float modifyCargoPrice;
    /**
     * 修改后的总价格
     */
    private float modifyTotalPrice;
    /**
     * 付款时间
     */
    private Date payTime;
    /**
     * 付款时间
     */
    private Date cargoTime;
    /**
     * 确定收货时间
     */
    private Date confirmCargoTime;
    private String iseff;
    private Date createTime;
    private Date lastUpdate;

    public Integer getNeedCargo() {
        return needCargo;
    }

    public void setNeedCargo(Integer needCargo) {
        this.needCargo = needCargo;
    }

    public float getModifyCargoPrice() {
        return modifyCargoPrice;
    }

    public void setModifyCargoPrice(float modifyCargoPrice) {
        this.modifyCargoPrice = modifyCargoPrice;
    }

    public float getModifyTotalPrice() {
        return modifyTotalPrice;
    }

    public void setModifyTotalPrice(float modifyTotalPrice) {
        this.modifyTotalPrice = modifyTotalPrice;
    }

    public Date getPayTime() {
        return payTime;
    }

    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    public Date getCargoTime() {
        return cargoTime;
    }

    public void setCargoTime(Date cargoTime) {
        this.cargoTime = cargoTime;
    }

    public Date getConfirmCargoTime() {
        return confirmCargoTime;
    }

    public void setConfirmCargoTime(Date confirmCargoTime) {
        this.confirmCargoTime = confirmCargoTime;
    }

    public OrderInfo() {
    }

    public String getCargoName() {
        return cargoName;
    }

    public void setCargoName(String cargoName) {
        this.cargoName = cargoName;
    }

    public String getCargoNumber() {
        return cargoNumber;
    }

    public void setCargoNumber(String cargoNumber) {
        this.cargoNumber = cargoNumber;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getBizId() {
        return this.bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public float getProductPrice() {
        return this.productPrice;
    }

    public void setProductPrice(float productPrice) {
        this.productPrice = productPrice;
    }

    public float getCargoPrice() {
        return this.cargoPrice;
    }

    public void setCargoPrice(float cargoPrice) {
        this.cargoPrice = cargoPrice;
    }

    public float getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIseff() {
        return this.iseff;
    }

    public void setIseff(String iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
