package com.ewing.busi.order.model;

// Generated 2016-2-4 17:41:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderRefund generated by hbm2java
 */
public class OrderRefund implements java.io.Serializable {

    private Integer id;
    private int orderId;
    private int orderDetailId;
    private char type;
    private int customerId;
    private int userId;
    private int resourceId;
    private int reasonType;
    private int reason;
    private Integer cargoNumber;
    private float refundMoney;
    private char status;
    private char iseff;
    private Date createTime;
    private Date lastUpdate;

    public OrderRefund() {
    }

    public OrderRefund(int orderId, int orderDetailId, char type, int customerId, int userId,
            int resourceId, int reasonType, int reason, float refundMoney, char status, char iseff,
            Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.refundMoney = refundMoney;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public OrderRefund(int orderId, int orderDetailId, char type, int customerId, int userId,
            int resourceId, int reasonType, int reason, Integer cargoNumber, float refundMoney,
            char status, char iseff, Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.cargoNumber = cargoNumber;
        this.refundMoney = refundMoney;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getOrderId() {
        return this.orderId;
    }

    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    public int getOrderDetailId() {
        return this.orderDetailId;
    }

    public void setOrderDetailId(int orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    public char getType() {
        return this.type;
    }

    public void setType(char type) {
        this.type = type;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(int resourceId) {
        this.resourceId = resourceId;
    }

    public int getReasonType() {
        return this.reasonType;
    }

    public void setReasonType(int reasonType) {
        this.reasonType = reasonType;
    }

    public int getReason() {
        return this.reason;
    }

    public void setReason(int reason) {
        this.reason = reason;
    }

    public Integer getCargoNumber() {
        return this.cargoNumber;
    }

    public void setCargoNumber(Integer cargoNumber) {
        this.cargoNumber = cargoNumber;
    }

    public float getRefundMoney() {
        return this.refundMoney;
    }

    public void setRefundMoney(float refundMoney) {
        this.refundMoney = refundMoney;
    }

    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    public char getIseff() {
        return this.iseff;
    }

    public void setIseff(char iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
