package com.ewing.busi.order.model;

// Generated 2016-4-5 16:57:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderProcessHistory generated by hbm2java
 */
public class OrderProcessHistory implements java.io.Serializable {

    private Integer id;
    private String bizId;
    private String busiType;
    private int busiId;
    private int customerId;
    private int userId;
    private String status;
    private String statusString;
    private String comment;
    private Date createTime;
    private Date lastUpdate;

    public OrderProcessHistory() {
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getBizId() {
        return this.bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public String getBusiType() {
        return this.busiType;
    }

    public void setBusiType(String busiType) {
        this.busiType = busiType;
    }

    public int getBusiId() {
        return this.busiId;
    }

    public void setBusiId(int busiId) {
        this.busiId = busiId;
    }

    public int getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatusString() {
        return this.statusString;
    }

    public void setStatusString(String statusString) {
        this.statusString = statusString;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
