package com.ewing.core.job.model;

// Generated 2016-2-16 11:51:43 by Hibernate Tools 3.4.0.CR1

/**
 * JobDefine generated by hbm2java
 */
public class JobDefine implements java.io.Serializable {

    private Integer id;
    private String cluster;
    private String name;
    private String jobCron;
    private String jobClass;
    private Integer isEnable;
    private Long createTime;
    private Long updateTime;

    public JobDefine() {
    }

    public JobDefine(String cluster, String name, String jobCron, String jobClass, long createTime) {
        this.cluster = cluster;
        this.name = name;
        this.jobCron = jobCron;
        this.jobClass = jobClass;
        this.createTime = createTime;
    }

    public JobDefine(String cluster, String name, String jobCron, String jobClass,
            Integer isEnable, long createTime, Long updateTime) {
        this.cluster = cluster;
        this.name = name;
        this.jobCron = jobCron;
        this.jobClass = jobClass;
        this.isEnable = isEnable;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCluster() {
        return this.cluster;
    }

    public void setCluster(String cluster) {
        this.cluster = cluster;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getJobCron() {
        return this.jobCron;
    }

    public void setJobCron(String jobCron) {
        this.jobCron = jobCron;
    }

    public String getJobClass() {
        return this.jobClass;
    }

    public void setJobClass(String jobClass) {
        this.jobClass = jobClass;
    }

    public Integer getIsEnable() {
        return this.isEnable;
    }

    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    public long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
