package com.ewing.core.job.model;

// Generated 2016-2-16 11:51:43 by Hibernate Tools 3.4.0.CR1

/**
 * JobProcessLog generated by hbm2java
 */
public class JobProcessLog implements java.io.Serializable {

    private Integer id;
    private String name;
    private int result;
    private String message;
    private Long createTime;
    private Long updateTime;

    public JobProcessLog() {
    }

    public JobProcessLog(String name, int result, long createTime) {
        this.name = name;
        this.result = result;
        this.createTime = createTime;
    }

    public JobProcessLog(String name, int result, String message, long createTime, Long updateTime) {
        this.name = name;
        this.result = result;
        this.message = message;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getResult() {
        return this.result;
    }

    public void setResult(int result) {
        this.result = result;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
