package com.ewing.core.job.model;

// Generated 2016-2-16 11:51:43 by Hibernate Tools 3.4.0.CR1

/**
 * JobVote generated by hbm2java
 */
public class JobVote implements java.io.Serializable {

    private Integer id;
    private String cluster;
    private String node;
    private Long createTime;
    private Long updateTime;

    public JobVote() {
    }

    public JobVote(String cluster, String node, long createTime) {
        this.cluster = cluster;
        this.node = node;
        this.createTime = createTime;
    }

    public JobVote(String cluster, String node, long createTime, Long updateTime) {
        this.cluster = cluster;
        this.node = node;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCluster() {
        return this.cluster;
    }

    public void setCluster(String cluster) {
        this.cluster = cluster;
    }

    public String getNode() {
        return this.node;
    }

    public void setNode(String node) {
        this.node = node;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

}
