package com.ewing.busi.seller.model;

// Generated 2016-2-16 11:51:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Seller generated by hbm2java
 */
public class Seller implements java.io.Serializable {

    private Integer id;
    private String userName;
    private Integer depId;
    private String password;
    private Character sex;
    private String phone;
    private String addr;
    private String zipcode;
    private String email;
    private Character iseff;
    private Date createTime;
    private Date lastUpdate;

    public Seller() {
    }

    public Seller(String userName, String password, Date createTime, Date lastUpdate) {
        this.userName = userName;
        this.password = password;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Seller(String userName, Integer depId, String password, Character sex, String phone,
            String addr, String zipcode, String email, Character iseff, Date createTime,
            Date lastUpdate) {
        this.userName = userName;
        this.depId = depId;
        this.password = password;
        this.sex = sex;
        this.phone = phone;
        this.addr = addr;
        this.zipcode = zipcode;
        this.email = email;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getDepId() {
        return this.depId;
    }

    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddr() {
        return this.addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Character getIseff() {
        return this.iseff;
    }

    public void setIseff(Character iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
